## Deliverable 2. Create a Customer Travel Destinations Map.

In [2]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [4]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("C:/Users/m122353/Documents/bootcamp/Module_6/World_Weather_Analysis/Weather_Database/WeatherPy_database.csv")
city_data_df.head()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,cloudiness,wind Speed,Current Description
0,0,Hermanus,ZA,-34.4187,19.2345,57.90,75,3,4.76,clear sky
1,1,Hobart,AU,-42.8794,147.3294,70.27,65,75,4.00,broken clouds
2,2,Busselton,AU,-33.6500,115.3333,53.10,58,3,7.14,clear sky
3,3,Miraflores,MX,19.2167,-98.8083,69.03,56,43,1.57,scattered clouds
4,4,Ushuaia,AR,-54.8000,-68.3000,55.06,44,40,18.41,scattered clouds

In [5]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90

In [6]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
preferred_cities_df=city_data_df.loc[(city_data_df["Max Temp"]<=max_temp) & (city_data_df["Max Temp"]>=min_temp)]

In [8]:
# 4a. Determine if there are any empty rows.
preferred_cities_df.count()

City_ID                203
City                   203
Country                203
Lat                    203
Lng                    203
Max Temp               203
Humidity               203
cloudiness             203
wind Speed             203
Current Description    203
dtype: int64

In [11]:
# 4b. Drop any empty rows and create a new DataFrame that doesnâ€™t have empty rows.
clean_df=preferred_cities_df.dropna()

In [12]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = clean_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
5,Victoria,HK,77.32,clear sky,22.2855,114.1577,
13,Uribia,CO,82.83,overcast clouds,11.7139,-72.2660,
17,Weligama,LK,76.89,overcast clouds,5.9667,80.4167,
21,Carutapera,BR,78.21,overcast clouds,-1.1950,-46.0200,
23,Salaga,GH,77.86,broken clouds,8.5508,-0.5188,
27,Japura,ID,75.27,overcast clouds,-0.3167,102.3500,
30,Umm Lajj,SA,81.39,clear sky,25.0213,37.2685,
32,Kapaa,US,82.38,light rain,22.0752,-159.3190,
34,Pangkalanbuun,ID,75.97,broken clouds,-2.6833,111.6167,
42,Boyolangu,ID,80.46,overcast clouds,-8.1181,111.8935,

In [ ]:
#api check
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
hotels = requests.get(base_url, params=params).json()

In [14]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.
for index, row in hotel_df.iterrows():
    # 6c. Get latitude and longitude from DataFrame
    lat = row["Lat"]
    lng = row["Lng"]
    params["location"] = f"{lat},{lng}"
    
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except(IndexError):
        print("Hotel not found ... skipping.")

Hotel not found ... skipping.
Hotel not found ... skipping.
Hotel not found ... skipping.
Hotel not found ... skipping.
Hotel not found ... skipping.
Hotel not found ... skipping.
Hotel not found ... skipping.
Hotel not found ... skipping.
Hotel not found ... skipping.
Hotel not found ... skipping.
Hotel not found ... skipping.
Hotel not found ... skipping.
Hotel not found ... skipping.

In [27]:
# 7. Drop the rows where there is no Hotel Name.
clean_hotel_df=hotel_df.loc[(hotel_df["Hotel Name"]!='')]

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
5,Victoria,HK,77.32,clear sky,22.2855,114.1577,Mini Hotel Central
13,Uribia,CO,82.83,overcast clouds,11.7139,-72.2660,Hotel Uribia
17,Weligama,LK,76.89,overcast clouds,5.9667,80.4167,Weligama Bay Resort
21,Carutapera,BR,78.21,overcast clouds,-1.1950,-46.0200,Lidera
23,Salaga,GH,77.86,broken clouds,8.5508,-0.5188,Bore Nada Guest House
...,...,...,...,...,...,...,...
690,Bundaberg,AU,80.22,overcast clouds,-24.8500,152.3500,Takalvan Motel
691,Siocon,PH,82.44,few clouds,7.7061,122.1353,ABS Hotel
695,Dicabisagan,PH,82.18,clear sky,17.0818,122.4157,Nancy Montanes Bernardo
698,Cuajinicuilapa,MX,78.21,broken clouds,16.4667,-98.4167,Pozo S. XVI
701,Papetoai,PF,83.79,overcast clouds,-17.4961,-149.8729,Fare Vaihere

In [28]:
# 8a. Create the output File (CSV)
output_data_file="WeatherPy_vacation.csv"

# 8b. Export the City_Data into a csv
clean_hotel_df.to_csv(output_data_file, index_label="City_ID")

In [31]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} Â°F</dd>
</dl>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[['Lat', 'Lng']]

In [32]:
# 11a. Add a marker layer for each city to the map. 

max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer=gmaps.marker_layer(locations, info_box_content=hotel_info)


fig.add_layer(marker_layer)

# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))